version: "3"

services:

  node_1:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /ne_cache/bin/node -uuid=72c76c69-2a03-45c6-9d3d-c382fb65e9a7 -addr=node_1 -port=8080

  node_2:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    environment:
      - SERVICE_NAME=node
      - UUID=699ffddb-fc08-4b97-b51f-e5efcdc95062
      - ADDR=node_2
      - PORT=8080
    command:
      - /bin/sh
      - -c
      - |
        /ne_cache/bin/$SERVICE_NAME -uuid=$UUID -addr=$ADDR -port=$PORT

  node_3:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    environment:
      - SERVICE_NAME=node
      - UUID=94459cf9-ae93-4c47-86bb-a8dc5b3863d7
      - ADDR=node_3
      - PORT=8080
    command:
      - /bin/sh
      - -c
      - |
        /ne_cache/bin/$SERVICE_NAME -uuid=$UUID -addr=$ADDR -port=$PORT

  node_manage:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    environment:
      - SERVICE_NAME=node_manage
    command:
      - /bin/sh
      - -c
      - |
        /ne_cache/bin/$SERVICE_NAME

  server:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    ports:
      - "8080:8080"
    environment:
      - SERVICE_NAME=server
    command:
      - /bin/sh
      - -c
      - |
        /ne_cache/bin/$SERVICE_NAME
