version: "3"

services:

  node_1:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        /ne_cache/bin/node -uuid=72c76c69-2a03-45c6-9d3d-c382fb65e9a7 -addr=node_1 -port=8080 -node_manager_addr=node_manage:8080

  node_2:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        /ne_cache/bin/node -uuid=699ffddb-fc08-4b97-b51f-e5efcdc95062 -addr=node_2 -port=8080 -node_manager_addr=node_manage:8080

  node_3:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        /ne_cache/bin/node -uuid=94459cf9-ae93-4c47-86bb-a8dc5b3863d7 -addr=node_3 -port=8080 -node_manager_addr=node_manage:8080

  node_manage:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    command:
      - /bin/sh
      - -c
      - |
        /ne_cache/bin/nodemanage

  server:
    image: ne_cache
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "10"
    ports:
      - "8080:8080"
    command:
      - /bin/sh
      - -c
      - |
        sleep 5
        /ne_cache/bin/server -node_manager_addr=node_manage:8080
